# -*- coding: utf-8 -*-
"""one_hot_encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gAukGwlbMjCHH9ukSuTKMj9ms9bvpd9
"""

import pandas as pd

df = pd.read_csv("homeprices.csv")
df

"""# Using pandas to create dummy variables"""

dummies = pd.get_dummies(df.town)
dummies = dummies.astype(int)
dummies

merged = pd.concat([df,dummies],axis='columns')
merged

final = merged.drop(['town'], axis='columns')
final

"""# Dummy Variable Trap"""

final = final.drop(['west windsor'], axis='columns')
final

X = final.drop('price', axis='columns')
X

y = final.price

from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(X,y)

model.predict(X)

model.score(X,y)

model.predict([[3400,0,0]])

model.predict([[2800,0,1]])

"""# Using sklearn OneHotEncoder"""

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

X = dfle[['town','area']].values

X

y = dfle.price.values
y

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

X = ct.fit_transform(X)
X

X = X[:,1:]

X

model.fit(X,y)

model.predict([[0,1,3400]])

model.predict([[1,0,2800]])

"""# Exercise"""

import pandas as pd
df = pd.read_csv("carprices.csv")
df

dummies = pd.get_dummies(df['Car Model'])
dummies = dummies.astype(int)
dummies

merged = pd.concat([df,dummies],axis='columns')
merged

final = merged.drop(["Car Model","Mercedez Benz C class"],axis='columns')
final

X = final.drop('Sell Price($)',axis='columns')
X

y = final['Sell Price($)']
y

from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(X,y)

model.score(X,y)

"""Price of mercedez benz that is 4 yr old with mileage **45000**"""

model.predict([[45000,4,0,0]])

"""Price of BMW X5 that is 7 yr old with mileage **86000**"""

model.predict([[86000,7,0,1]])