# -*- coding: utf-8 -*-
"""decision tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHXqYTMty5BtM2OkjACQtzvsSXaccEA7
"""

import pandas as pd

df = pd.read_csv("salaries.csv")
df.head()

inputs = df.drop('salary_more_then_100k',axis='columns')

target = df['salary_more_then_100k']

from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_job.fit_transform(inputs['job'])
inputs['degree_n'] = le_degree.fit_transform(inputs['degree'])

inputs

inputs_n = inputs.drop(['company','job','degree'],axis='columns')

inputs_n

target

from sklearn import tree
model = tree.DecisionTreeClassifier()

model.fit(inputs_n, target)

model.score(inputs_n,target)

"""Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?"""

model.predict([[2,1,0]])

"""Is salary of Google, Computer Engineer, Masters degree > 100 k ?"""

model.predict([[2,1,1]])

"""# Exercise: Build decision tree model to predict survival based on certain parameters"""

import pandas as pd

d = pd.read_csv("titanic.csv")
d.head()

d.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

d.head()

inputs = d.drop('Survived',axis='columns')
target = d.Survived

inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

inputs.Age[:10]

inputs.Age = inputs.Age.fillna(inputs.Age.mean())

inputs.head()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

len(X_train)

len(X_test)

from sklearn import tree
model = tree.DecisionTreeClassifier()

model.fit(X_train,y_train)

model.score(X_test,y_test)